### PR TITLE
Support latest ctrtool

### PR DESCRIPTION
**Pull request by leo60228**
When writing ctrtool support, I was using NixOS's ctrtool package, which turned out to be out of date. This PR updates the parsing to handle the very different output format used starting in ctrtool 1.0.0.

Note that (presumably due to UB) ctrtool 1.0.0+ has broken CIA support with compiler optimizations enabled.

### CODE REVIEW

**Comment by alucryd** [comment]
Thanks! I'm going to put CIA to the test after I release 0.17.0. I registered to the no-intro forums as I can't find a CDN 3DS DAT in the daily datomatic love pack I regularly use, hopefully that gives me access to more DATs.

Maybe building ctrtool with clang instead of GCC will help with the CIA issue, I'll update the Arch Linux package if the one I built doesn't work as expected.

**Comment by leo60228** [comment]
> I registered to the no-intro forums as I can't find a CDN 3DS DAT in the daily datomatic love pack I regularly use, hopefully that gives me access to more DATs.

It seems to be at `No-Intro/Nintendo - Nintendo 3DS (Digital) (CDN) (20231011-123410).dat` in `No-Intro Love Pack (Standard) (2023-11-02).zip`, maybe it was missing from yesterday's for some reason?

**Comment by Immersion95** [comment]
I imported the 3DS CDN Digital .dat but it doesn't import games in the respective subfolders, the "00000000" and "0000000A" are replacing eachother in the "Nintendo - Nintendo 3DS" folder.

ALso, I can't convert CDN to CIA, inly have these options : 
Please select systems: Nintendo - Nintendo 3DS (Digital) (CDN)
Please select a format:
  ORIGINAL
  7Z
  ZIP
  CHD
  CSO
  NSZ
  RVZ

**Comment by leo60228** [comment]
The intended usecase is being able to import the CDN DAT and then manage CIA files the same way you could ROMs for any other system. I haven't implemented conversion from CDN to CIA because CIA files include a ticket that No-Intro doesn't currently DAT (though I think I saw a mention of it possibly being included in the future with console-specific information removed?).

To solve the issue with CDN files overwriting each other, you can import the CDN DAT with `--arcade`. From my understanding, that flag actually means that each game should be treated as a folder with multiple files in it.

**Comment by leo60228** [comment]
In hindsight, the PR description probably should have clarified this better, though I think it was clear from the code. At the time, I assumed it was implied by the mention that CIA files include more information than what No-Intro DATs.

**Pull request merged**
